export const SET_INITIALIZED = 'SET_INITIALIZED';

export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const READ_EDUCATIONS = 'READ_EDUCATIONS';
export const READ_EDUCATION = 'READ_EDUCATION';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const SET_EDUCATIONS = 'SET_EDUCATIONS';

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const READ_LANGUAGES = 'READ_LANGUAGES';
export const READ_LANGUAGE = 'READ_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
export const SET_LANGUAGES = 'SET_LANGUAGES';

export const CREATE_PARAGRAPH = 'CREATE_PARAGRAPH';
export const READ_PARAGRAPHS = 'READ_PARAGRAPHS';
export const READ_PARAGRAPH = 'READ_PARAGRAPH';
export const UPDATE_PARAGRAPH = 'UPDATE_PARAGRAPH';
export const DELETE_PARAGRAPH = 'DELETE_PARAGRAPH';
export const SET_PARAGRAPHS = 'SET_PARAGRAPHS';

export const CREATE_POSITION = 'CREATE_POSITION';
export const READ_POSITIONS = 'READ_POSITIONS';
export const READ_POSITION = 'READ_POSITION';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const DELETE_POSITION = 'DELETE_POSITION';
export const SET_POSITIONS = 'SET_POSITIONS';

export const CREATE_USER = 'CREATE_USER';
export const READ_USERS = 'READ_USERS';
export const READ_USER = 'READ_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_USERS = 'SET_USERS';

export const CREATE_WORKHISTORY = 'CREATE_WORKHISTORY';
export const READ_WORKHISTORIES = 'READ_WORKHISTORIES';
export const READ_WORKHISTORY = 'READ_WORKHISTORY';
export const UPDATE_WORKHISTORY = 'UPDATE_WORKHISTORY';
export const DELETE_WORKHISTORY = 'DELETE_WORKHISTORY';
export const SET_WORKHISTORIES = 'SET_WORKHISTORIES';

